export { default as auth } from './auth'
export { default as user } from './user'
export { default as person } from './person'
export { default as pokemon } from './pokemon'
export { default as rol } from './rol'
